// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type Book struct {
	Uuid        int64  `json:"uuid"`
	Name        string `json:"name"`
	Publication string `json:"publication"`
}
